services:
  pattern-php:
    container_name: dev-php8-3
    build:
      dockerfile: docker/Dockerfile-debug
    environment:
      - 'VHOST=localhost'
      - 'XDEBUG_MODE=coverage,debug'
      - 'XDEBUG_CLIENT_HOST=host.docker.internal'
      - 'XDEBUG_LOG=/var/log'
    volumes:
      - ./:/app
    networks:
      - patterns-network

  composer:
    container_name: pattern-composer
    image: composer:latest
    command: [ "composer", "${CMD:-dump-autoload}", "--ignore-platform-reqs" ]
    volumes:
      - ./:/app
    networks:
      - patterns-network

networks:
  patterns-network:
    driver: bridge
